
package br.edu.ifpb.ads.pos.soap.trip.voo.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Voos", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Voos {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "salvar", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.voo.ws.Salvar")
    @ResponseWrapper(localName = "salvarResponse", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.voo.ws.SalvarResponse")
    public void salvar(
        @WebParam(name = "arg0", targetNamespace = "")
        Voo arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletar", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.voo.ws.Deletar")
    @ResponseWrapper(localName = "deletarResponse", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.voo.ws.DeletarResponse")
    public void deletar(
        @WebParam(name = "arg0", targetNamespace = "")
        Voo arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.edu.ifpb.ads.pos.soap.trip.voo.ws.VooEmb
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscar", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.voo.ws.Buscar")
    @ResponseWrapper(localName = "buscarResponse", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.voo.ws.BuscarResponse")
    public VooEmb buscar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifpb.ads.pos.soap.trip.voo.ws.VooEmb>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listar", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.voo.ws.Listar")
    @ResponseWrapper(localName = "listarResponse", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.voo.ws.ListarResponse")
    public List<VooEmb> listar();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "atualizar", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.voo.ws.Atualizar")
    @ResponseWrapper(localName = "atualizarResponse", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.voo.ws.AtualizarResponse")
    public void atualizar(
        @WebParam(name = "arg0", targetNamespace = "")
        Voo arg0);

}
