
package br.edu.ifpb.ads.pos.soap.trip.quarto.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "QuartosService", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", wsdlLocation = "http://localhost:8080/pos-soap-trip-hotel/QuartosService?WSDL")
public class QuartosService
    extends Service
{

    private final static URL QUARTOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUARTOSSERVICE_EXCEPTION;
    private final static QName QUARTOSSERVICE_QNAME = new QName("http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", "QuartosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pos-soap-trip-hotel/QuartosService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUARTOSSERVICE_WSDL_LOCATION = url;
        QUARTOSSERVICE_EXCEPTION = e;
    }

    public QuartosService() {
        super(__getWsdlLocation(), QUARTOSSERVICE_QNAME);
    }

    public QuartosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Quartos
     */
    @WebEndpoint(name = "QuartosPort")
    public Quartos getQuartosPort() {
        return super.getPort(new QName("http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", "QuartosPort"), Quartos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Quartos
     */
    @WebEndpoint(name = "QuartosPort")
    public Quartos getQuartosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", "QuartosPort"), Quartos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUARTOSSERVICE_EXCEPTION!= null) {
            throw QUARTOSSERVICE_EXCEPTION;
        }
        return QUARTOSSERVICE_WSDL_LOCATION;
    }

}
