
package br.edu.ifpb.ads.pos.soap.trip.quarto.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Quartos", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Quartos {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.edu.ifpb.ads.pos.soap.trip.quarto.ws.Quarto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarByHotelNome", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.quarto.ws.BuscarByHotelNome")
    @ResponseWrapper(localName = "buscarByHotelNomeResponse", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.quarto.ws.BuscarByHotelNomeResponse")
    public List<Quarto> buscarByHotelNome(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifpb.ads.pos.soap.trip.quarto.ws.Quarto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarQuarto", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.quarto.ws.ListarQuarto")
    @ResponseWrapper(localName = "listarQuartoResponse", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.quarto.ws.ListarQuartoResponse")
    public List<Quarto> listarQuarto();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "salvarQuarto", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.quarto.ws.SalvarQuarto")
    @ResponseWrapper(localName = "salvarQuartoResponse", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.quarto.ws.SalvarQuartoResponse")
    public void salvarQuarto(
        @WebParam(name = "arg0", targetNamespace = "")
        Quarto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "atualizarQuarto", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.quarto.ws.AtualizarQuarto")
    @ResponseWrapper(localName = "atualizarQuartoResponse", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.quarto.ws.AtualizarQuartoResponse")
    public void atualizarQuarto(
        @WebParam(name = "arg0", targetNamespace = "")
        Quarto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletarQuarto", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.quarto.ws.DeletarQuarto")
    @ResponseWrapper(localName = "deletarQuartoResponse", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.quarto.ws.DeletarQuartoResponse")
    public void deletarQuarto(
        @WebParam(name = "arg0", targetNamespace = "")
        Quarto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.edu.ifpb.ads.pos.soap.trip.quarto.ws.Quarto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarQuarto", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.quarto.ws.BuscarQuarto")
    @ResponseWrapper(localName = "buscarQuartoResponse", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.quarto.ws.BuscarQuartoResponse")
    public Quarto buscarQuarto(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
