
package br.edu.ifpb.ads.pos.soap.trip.hotel.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HoteisService", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", wsdlLocation = "http://localhost:8080/pos-soap-trip-hotel/HoteisService?WSDL")
public class HoteisService
    extends Service
{

    private final static URL HOTEISSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTEISSERVICE_EXCEPTION;
    private final static QName HOTEISSERVICE_QNAME = new QName("http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", "HoteisService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pos-soap-trip-hotel/HoteisService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTEISSERVICE_WSDL_LOCATION = url;
        HOTEISSERVICE_EXCEPTION = e;
    }

    public HoteisService() {
        super(__getWsdlLocation(), HOTEISSERVICE_QNAME);
    }

    public HoteisService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Hoteis
     */
    @WebEndpoint(name = "HoteisPort")
    public Hoteis getHoteisPort() {
        return super.getPort(new QName("http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", "HoteisPort"), Hoteis.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Hoteis
     */
    @WebEndpoint(name = "HoteisPort")
    public Hoteis getHoteisPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", "HoteisPort"), Hoteis.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTEISSERVICE_EXCEPTION!= null) {
            throw HOTEISSERVICE_EXCEPTION;
        }
        return HOTEISSERVICE_WSDL_LOCATION;
    }

}
