
package br.edu.ifpb.ads.pos.soap.trip.passagem.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Passagens", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Passagens {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "atualizarPassagem", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.AtualizarPassagem")
    @ResponseWrapper(localName = "atualizarPassagemResponse", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.AtualizarPassagemResponse")
    public void atualizarPassagem(
        @WebParam(name = "arg0", targetNamespace = "")
        Passagem arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletarPassagem", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.DeletarPassagem")
    @ResponseWrapper(localName = "deletarPassagemResponse", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.DeletarPassagemResponse")
    public void deletarPassagem(
        @WebParam(name = "arg0", targetNamespace = "")
        Passagem arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.edu.ifpb.ads.pos.soap.trip.passagem.ws.Passagem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarPassagem", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.BuscarPassagem")
    @ResponseWrapper(localName = "buscarPassagemResponse", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.BuscarPassagemResponse")
    public Passagem buscarPassagem(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.edu.ifpb.ads.pos.soap.trip.passagem.ws.Passagem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarPassagemByCode", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.BuscarPassagemByCode")
    @ResponseWrapper(localName = "buscarPassagemByCodeResponse", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.BuscarPassagemByCodeResponse")
    public Passagem buscarPassagemByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.edu.ifpb.ads.pos.soap.trip.passagem.ws.Passagem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarPassagemByVooCode", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.BuscarPassagemByVooCode")
    @ResponseWrapper(localName = "buscarPassagemByVooCodeResponse", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.BuscarPassagemByVooCodeResponse")
    public List<Passagem> buscarPassagemByVooCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifpb.ads.pos.soap.trip.passagem.ws.Passagem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPassagens", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.ListarPassagens")
    @ResponseWrapper(localName = "listarPassagensResponse", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.ListarPassagensResponse")
    public List<Passagem> listarPassagens();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "salvarPassagem", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.SalvarPassagem")
    @ResponseWrapper(localName = "salvarPassagemResponse", targetNamespace = "http://service.passagem.trip.soap.pos.ads.ifpb.edu.br/", className = "br.edu.ifpb.ads.pos.soap.trip.passagem.ws.SalvarPassagemResponse")
    public void salvarPassagem(
        @WebParam(name = "arg0", targetNamespace = "")
        Passagem arg0);

}
