
package br.edu.ifpb.ads.pos.soap.trip.reserva.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ReservasService", targetNamespace = "http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", wsdlLocation = "http://localhost:8080/pos-soap-trip-hotel/ReservasService?WSDL")
public class ReservasService
    extends Service
{

    private final static URL RESERVASSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESERVASSERVICE_EXCEPTION;
    private final static QName RESERVASSERVICE_QNAME = new QName("http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", "ReservasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pos-soap-trip-hotel/ReservasService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVASSERVICE_WSDL_LOCATION = url;
        RESERVASSERVICE_EXCEPTION = e;
    }

    public ReservasService() {
        super(__getWsdlLocation(), RESERVASSERVICE_QNAME);
    }

    public ReservasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Reservas
     */
    @WebEndpoint(name = "ReservasPort")
    public Reservas getReservasPort() {
        return super.getPort(new QName("http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", "ReservasPort"), Reservas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Reservas
     */
    @WebEndpoint(name = "ReservasPort")
    public Reservas getReservasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.hotel.trip.soap.pos.ads.ifpb.edu.br/", "ReservasPort"), Reservas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVASSERVICE_EXCEPTION!= null) {
            throw RESERVASSERVICE_EXCEPTION;
        }
        return RESERVASSERVICE_WSDL_LOCATION;
    }

}
