
package br.edu.ifpb.ads.pos.soap.trip.cliente.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ClientesService", targetNamespace = "http://service.cliente.trip.soap.pos.ads.ifpb.edu.br/", wsdlLocation = "http://localhost:8080/pos-soap-trip-cliente/ClientesService?WSDL")
public class ClientesService
    extends Service
{

    private final static URL CLIENTESSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTESSERVICE_EXCEPTION;
    private final static QName CLIENTESSERVICE_QNAME = new QName("http://service.cliente.trip.soap.pos.ads.ifpb.edu.br/", "ClientesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pos-soap-trip-cliente/ClientesService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTESSERVICE_WSDL_LOCATION = url;
        CLIENTESSERVICE_EXCEPTION = e;
    }

    public ClientesService() {
        super(__getWsdlLocation(), CLIENTESSERVICE_QNAME);
    }

    public ClientesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Clientes
     */
    @WebEndpoint(name = "ClientesPort")
    public Clientes getClientesPort() {
        return super.getPort(new QName("http://service.cliente.trip.soap.pos.ads.ifpb.edu.br/", "ClientesPort"), Clientes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Clientes
     */
    @WebEndpoint(name = "ClientesPort")
    public Clientes getClientesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cliente.trip.soap.pos.ads.ifpb.edu.br/", "ClientesPort"), Clientes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTESSERVICE_EXCEPTION!= null) {
            throw CLIENTESSERVICE_EXCEPTION;
        }
        return CLIENTESSERVICE_WSDL_LOCATION;
    }

}
